version: '{branch}-{build}'

configuration: Release

before_build:
- cmd: nuget restore

for:

#configuration for master branch
- 
  branches:
    only: 
      - master

  environment:
    nuget_version: 0.9.1

  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '$env:nuget_version'
    version_prefix: '$env:nuget_version'
    package_version: '$env:nuget_version'
    assembly_version: '$env:nuget_version'
    file_version: '$env:nuget_version'
    informational_version: '$env:nuget_version'

  build:
    publish_nuget: true
    verbosity: minimal
  
  artifacts:
    - path: .\PandaSharp.Bamboo\bin\Release
      name: PandaSharp
  
    - path: '**\*.nupkg'
  
#configuration for all other branches
-
  branches:
    except: 
      - master

  build:
    publish_nuget: false
    verbosity: minimal
  
  artifacts:
    - path: .\PandaSharp.Bamboo\bin\Release
      name: PandaSharp